"""Strecken-Daten für Radgame.

Jeder Eintrag ist eine vereinfachte, spieltaugliche Version einer echten Strecke.
Die `distance_m` ist die im Spiel zurückzulegende Distanz (skaliert, nicht real).
`real_distance_km` und `race` sind Flavor-Felder für die UI.

Felder:
    id                eindeutiger Schlüssel (für Save-File / Bestplatzierungen)
    name              Anzeigename
    race              Wettkampf-Kontext (z. B. "Tour de France")
    region            geographische Region
    distance_m        Spiel-Distanz in Metern
    real_distance_km  reale Streckenlänge (nur Anzeige)
    difficulty        1–5 (Sterne)
    opponents         Anzahl KI-Gegner
    obstacle_density  Rate für Hindernis-Spawn (1.0 = normal)
    wind              0..1, beeinflusst Seitendrift + Energieverbrauch
    heat              0..1, beeinflusst Energieverbrauch
    surface           "asphalt" | "cobbles" | "gravel"  (Flavor + spätere Mechanik)
    theme             optisches Thema (Farben, Deko, Hindernis-Mix, Kurven-Schärfe):
                      "coast" | "classic" | "cobbles" | "gravel" |
                      "mountain" | "alpine" | "autumn" |
                      "polder" | "heath" | "dolomites" | "desert" |
                      "volcanic" | "bretagne"
"""

ROUTES = [
    {
        "id": "milano_sanremo",
        "name": "Mailand – Sanremo",
        "race": "Monument",
        "region": "Italien",
        "distance_m": 1400,
        "real_distance_km": 293,
        "difficulty": 2,
        "opponents": 5,
        "obstacle_density": 0.6,
        "wind": 0.3,
        "heat": 0.4,
        "surface": "asphalt",
        "theme": "coast",
    },
    {
        "id": "strade_bianche",
        "name": "Strade Bianche",
        "race": "Klassiker (Schotter)",
        "region": "Toskana, Italien",
        "distance_m": 1600,
        "real_distance_km": 184,
        "difficulty": 3,
        "opponents": 5,
        "obstacle_density": 1.2,
        "wind": 0.3,
        "heat": 0.6,
        "surface": "gravel",
        "theme": "gravel",
    },
    {
        "id": "flandern",
        "name": "Ronde van Vlaanderen",
        "race": "Monument",
        "region": "Belgien",
        "distance_m": 1700,
        "real_distance_km": 270,
        "difficulty": 3,
        "opponents": 6,
        "obstacle_density": 1.0,
        "wind": 0.5,
        "heat": 0.1,
        "surface": "cobbles",
        "theme": "cobbles",
    },
    {
        "id": "paris_roubaix",
        "name": "Paris – Roubaix",
        "race": "Monument – Hölle des Nordens",
        "region": "Frankreich/Belgien",
        "distance_m": 1800,
        "real_distance_km": 257,
        "difficulty": 4,
        "opponents": 6,
        "obstacle_density": 1.6,
        "wind": 0.4,
        "heat": 0.2,
        "surface": "cobbles",
        "theme": "cobbles",
    },
    {
        "id": "liege",
        "name": "Lüttich – Bastogne – Lüttich",
        "race": "Monument",
        "region": "Ardennen, Belgien",
        "distance_m": 1700,
        "real_distance_km": 257,
        "difficulty": 3,
        "opponents": 5,
        "obstacle_density": 0.7,
        "wind": 0.3,
        "heat": 0.3,
        "surface": "asphalt",
        "theme": "classic",
    },
    {
        "id": "tourmalet",
        "name": "Col du Tourmalet",
        "race": "Tour de France",
        "region": "Pyrenäen, Frankreich",
        "distance_m": 1850,
        "real_distance_km": 19,
        "difficulty": 4,
        "opponents": 6,
        "obstacle_density": 0.6,
        "wind": 0.6,
        "heat": 0.4,
        "surface": "asphalt",
        "theme": "mountain",
    },
    {
        "id": "alpedhuez",
        "name": "Alpe d'Huez",
        "race": "Tour de France",
        "region": "Alpen, Frankreich",
        "distance_m": 1900,
        "real_distance_km": 14,
        "difficulty": 4,
        "opponents": 7,
        "obstacle_density": 0.6,
        "wind": 0.4,
        "heat": 0.6,
        "surface": "asphalt",
        "theme": "mountain",
    },
    {
        "id": "galibier",
        "name": "Col du Galibier",
        "race": "Tour de France",
        "region": "Alpen, Frankreich",
        "distance_m": 1900,
        "real_distance_km": 23,
        "difficulty": 4,
        "opponents": 6,
        "obstacle_density": 0.6,
        "wind": 0.7,
        "heat": 0.4,
        "surface": "asphalt",
        "theme": "mountain",
    },
    {
        "id": "ventoux",
        "name": "Mont Ventoux",
        "race": "Tour de France",
        "region": "Provence, Frankreich",
        "distance_m": 2000,
        "real_distance_km": 22,
        "difficulty": 5,
        "opponents": 7,
        "obstacle_density": 0.7,
        "wind": 0.9,
        "heat": 0.8,
        "surface": "asphalt",
        "theme": "mountain",
    },
    {
        "id": "mortirolo",
        "name": "Passo del Mortirolo",
        "race": "Giro d'Italia",
        "region": "Lombardei, Italien",
        "distance_m": 1950,
        "real_distance_km": 12,
        "difficulty": 5,
        "opponents": 6,
        "obstacle_density": 0.7,
        "wind": 0.4,
        "heat": 0.5,
        "surface": "asphalt",
        "theme": "mountain",
    },
    {
        "id": "zoncolan",
        "name": "Monte Zoncolan",
        "race": "Giro d'Italia",
        "region": "Friaul, Italien",
        "distance_m": 1950,
        "real_distance_km": 10,
        "difficulty": 5,
        "opponents": 7,
        "obstacle_density": 0.7,
        "wind": 0.4,
        "heat": 0.6,
        "surface": "asphalt",
        "theme": "mountain",
    },
    {
        "id": "stelvio",
        "name": "Passo dello Stelvio",
        "race": "Giro d'Italia – Cima Coppi",
        "region": "Südtirol, Italien",
        "distance_m": 2000,
        "real_distance_km": 24,
        "difficulty": 5,
        "opponents": 7,
        "obstacle_density": 0.6,
        "wind": 0.7,
        "heat": 0.4,
        "surface": "asphalt",
        "theme": "alpine",
    },
    {
        "id": "angliru",
        "name": "Alto de l'Angliru",
        "race": "Vuelta a España",
        "region": "Asturien, Spanien",
        "distance_m": 2000,
        "real_distance_km": 12,
        "difficulty": 5,
        "opponents": 7,
        "obstacle_density": 0.8,
        "wind": 0.5,
        "heat": 0.5,
        "surface": "asphalt",
        "theme": "mountain",
    },
    {
        "id": "lombardia",
        "name": "Il Lombardia",
        "race": "Monument – Klassiker der fallenden Blätter",
        "region": "Lombardei, Italien",
        "distance_m": 1750,
        "real_distance_km": 238,
        "difficulty": 3,
        "opponents": 6,
        "obstacle_density": 0.7,
        "wind": 0.3,
        "heat": 0.2,
        "surface": "asphalt",
        "theme": "autumn",
    },
    {
        "id": "het_nieuwsblad",
        "name": "Omloop Het Nieuwsblad",
        "race": "Klassiker — Eröffnungsrennen",
        "region": "Flandern, Belgien",
        "distance_m": 1500,
        "real_distance_km": 200,
        "difficulty": 2,
        "opponents": 5,
        "obstacle_density": 1.1,
        "wind": 0.5,
        "heat": 0.1,
        "surface": "cobbles",
        "theme": "cobbles",
    },
    {
        "id": "e3_saxo",
        "name": "E3 Saxo Classic",
        "race": "Klassiker",
        "region": "Harelbeke, Belgien",
        "distance_m": 1600,
        "real_distance_km": 204,
        "difficulty": 3,
        "opponents": 6,
        "obstacle_density": 1.2,
        "wind": 0.4,
        "heat": 0.2,
        "surface": "cobbles",
        "theme": "cobbles",
    },
    {
        "id": "gent_wevelgem",
        "name": "Gent–Wevelgem",
        "race": "Klassiker — Sturm an der Küste",
        "region": "Westflandern, Belgien",
        "distance_m": 1600,
        "real_distance_km": 250,
        "difficulty": 3,
        "opponents": 6,
        "obstacle_density": 0.8,
        "wind": 0.8,
        "heat": 0.2,
        "surface": "asphalt",
        "theme": "polder",
    },
    {
        "id": "amstel_gold",
        "name": "Amstel Gold Race",
        "race": "Klassiker — Ardennenwoche",
        "region": "Limburg, Niederlande",
        "distance_m": 1650,
        "real_distance_km": 254,
        "difficulty": 3,
        "opponents": 6,
        "obstacle_density": 0.8,
        "wind": 0.3,
        "heat": 0.3,
        "surface": "asphalt",
        "theme": "heath",
    },
    {
        "id": "fleche_wallonne",
        "name": "La Flèche Wallonne",
        "race": "Klassiker — Mur de Huy",
        "region": "Wallonien, Belgien",
        "distance_m": 1700,
        "real_distance_km": 194,
        "difficulty": 4,
        "opponents": 6,
        "obstacle_density": 0.7,
        "wind": 0.3,
        "heat": 0.4,
        "surface": "asphalt",
        "theme": "classic",
    },
    {
        "id": "tro_bro_leon",
        "name": "Tro-Bro Léon",
        "race": "Klassiker — Bretonisches Paris–Roubaix",
        "region": "Bretagne, Frankreich",
        "distance_m": 1700,
        "real_distance_km": 207,
        "difficulty": 3,
        "opponents": 6,
        "obstacle_density": 1.3,
        "wind": 0.6,
        "heat": 0.2,
        "surface": "gravel",
        "theme": "bretagne",
    },
    {
        "id": "izoard",
        "name": "Col d'Izoard",
        "race": "Tour de France — Casse Déserte",
        "region": "Hautes-Alpes, Frankreich",
        "distance_m": 1850,
        "real_distance_km": 19,
        "difficulty": 4,
        "opponents": 6,
        "obstacle_density": 0.7,
        "wind": 0.5,
        "heat": 0.5,
        "surface": "asphalt",
        "theme": "mountain",
    },
    {
        "id": "gavia",
        "name": "Passo Gavia",
        "race": "Giro d'Italia",
        "region": "Lombardei, Italien",
        "distance_m": 1950,
        "real_distance_km": 25,
        "difficulty": 5,
        "opponents": 6,
        "obstacle_density": 0.7,
        "wind": 0.6,
        "heat": 0.3,
        "surface": "asphalt",
        "theme": "alpine",
    },
    {
        "id": "pordoi",
        "name": "Passo Pordoi",
        "race": "Giro d'Italia — Dolomiten",
        "region": "Trentino, Italien",
        "distance_m": 1900,
        "real_distance_km": 11,
        "difficulty": 4,
        "opponents": 6,
        "obstacle_density": 0.6,
        "wind": 0.5,
        "heat": 0.4,
        "surface": "asphalt",
        "theme": "dolomites",
    },
    {
        "id": "plan_de_corones",
        "name": "Plan de Corones",
        "race": "Giro d'Italia — Bergankunft",
        "region": "Südtirol, Italien",
        "distance_m": 1950,
        "real_distance_km": 12,
        "difficulty": 5,
        "opponents": 6,
        "obstacle_density": 0.7,
        "wind": 0.4,
        "heat": 0.4,
        "surface": "asphalt",
        "theme": "dolomites",
    },
    {
        "id": "covadonga",
        "name": "Lagos de Covadonga",
        "race": "Vuelta a España",
        "region": "Asturien, Spanien",
        "distance_m": 1900,
        "real_distance_km": 13,
        "difficulty": 4,
        "opponents": 7,
        "obstacle_density": 0.7,
        "wind": 0.4,
        "heat": 0.5,
        "surface": "asphalt",
        "theme": "mountain",
    },
    {
        "id": "sierra_nevada",
        "name": "Sierra Nevada",
        "race": "Vuelta a España",
        "region": "Andalusien, Spanien",
        "distance_m": 1950,
        "real_distance_km": 32,
        "difficulty": 5,
        "opponents": 7,
        "obstacle_density": 0.7,
        "wind": 0.5,
        "heat": 0.9,
        "surface": "asphalt",
        "theme": "desert",
    },
    {
        "id": "bola_del_mundo",
        "name": "Bola del Mundo",
        "race": "Vuelta a España — Sierra de Madrid",
        "region": "Madrid, Spanien",
        "distance_m": 1900,
        "real_distance_km": 22,
        "difficulty": 5,
        "opponents": 7,
        "obstacle_density": 0.8,
        "wind": 0.5,
        "heat": 0.7,
        "surface": "asphalt",
        "theme": "desert",
    },
    {
        "id": "etna",
        "name": "Mount Etna",
        "race": "Giro d'Italia — Sizilien",
        "region": "Sizilien, Italien",
        "distance_m": 2000,
        "real_distance_km": 24,
        "difficulty": 5,
        "opponents": 7,
        "obstacle_density": 0.9,
        "wind": 0.5,
        "heat": 0.8,
        "surface": "asphalt",
        "theme": "volcanic",
    },
]


def route_by_id(rid):
    return next((r for r in ROUTES if r["id"] == rid), None)
