"""Strecken-Daten für Radgame.

Jeder Eintrag ist eine vereinfachte, spieltaugliche Version einer echten Strecke.
Die `distance_m` ist die im Spiel zurückzulegende Distanz (skaliert, nicht real).
`real_distance_km` und `race` sind Flavor-Felder für die UI.

Felder:
    id                eindeutiger Schlüssel (für Save-File / Bestplatzierungen)
    name              Anzeigename
    race              Wettkampf-Kontext (z. B. "Tour de France")
    region            geographische Region
    distance_m        Spiel-Distanz in Metern
    real_distance_km  reale Streckenlänge (nur Anzeige)
    difficulty        1–5 (Sterne)
    opponents         Anzahl KI-Gegner
    obstacle_density  Rate für Hindernis-Spawn (1.0 = normal)
    wind              0..1, beeinflusst Seitendrift + Energieverbrauch
    heat              0..1, beeinflusst Energieverbrauch
    surface           "asphalt" | "cobbles" | "gravel"  (Flavor + spätere Mechanik)
"""

ROUTES = [
    {
        "id": "milano_sanremo",
        "name": "Mailand – Sanremo",
        "race": "Monument",
        "region": "Italien",
        "distance_m": 1500,
        "real_distance_km": 293,
        "difficulty": 2,
        "opponents": 5,
        "obstacle_density": 0.6,
        "wind": 0.3,
        "heat": 0.4,
        "surface": "asphalt",
    },
    {
        "id": "strade_bianche",
        "name": "Strade Bianche",
        "race": "Klassiker (Schotter)",
        "region": "Toskana, Italien",
        "distance_m": 1700,
        "real_distance_km": 184,
        "difficulty": 3,
        "opponents": 5,
        "obstacle_density": 1.2,
        "wind": 0.3,
        "heat": 0.6,
        "surface": "gravel",
    },
    {
        "id": "flandern",
        "name": "Ronde van Vlaanderen",
        "race": "Monument",
        "region": "Belgien",
        "distance_m": 1800,
        "real_distance_km": 270,
        "difficulty": 3,
        "opponents": 6,
        "obstacle_density": 1.0,
        "wind": 0.5,
        "heat": 0.1,
        "surface": "cobbles",
    },
    {
        "id": "paris_roubaix",
        "name": "Paris – Roubaix",
        "race": "Monument – Hölle des Nordens",
        "region": "Frankreich/Belgien",
        "distance_m": 2100,
        "real_distance_km": 257,
        "difficulty": 4,
        "opponents": 6,
        "obstacle_density": 1.6,
        "wind": 0.4,
        "heat": 0.2,
        "surface": "cobbles",
    },
    {
        "id": "liege",
        "name": "Lüttich – Bastogne – Lüttich",
        "race": "Monument",
        "region": "Ardennen, Belgien",
        "distance_m": 2000,
        "real_distance_km": 257,
        "difficulty": 3,
        "opponents": 5,
        "obstacle_density": 0.7,
        "wind": 0.3,
        "heat": 0.3,
        "surface": "asphalt",
    },
    {
        "id": "tourmalet",
        "name": "Col du Tourmalet",
        "race": "Tour de France",
        "region": "Pyrenäen, Frankreich",
        "distance_m": 2250,
        "real_distance_km": 19,
        "difficulty": 4,
        "opponents": 6,
        "obstacle_density": 0.6,
        "wind": 0.6,
        "heat": 0.4,
        "surface": "asphalt",
    },
    {
        "id": "alpedhuez",
        "name": "Alpe d'Huez",
        "race": "Tour de France",
        "region": "Alpen, Frankreich",
        "distance_m": 2400,
        "real_distance_km": 14,
        "difficulty": 4,
        "opponents": 7,
        "obstacle_density": 0.6,
        "wind": 0.4,
        "heat": 0.6,
        "surface": "asphalt",
    },
    {
        "id": "galibier",
        "name": "Col du Galibier",
        "race": "Tour de France",
        "region": "Alpen, Frankreich",
        "distance_m": 2500,
        "real_distance_km": 23,
        "difficulty": 4,
        "opponents": 6,
        "obstacle_density": 0.6,
        "wind": 0.7,
        "heat": 0.4,
        "surface": "asphalt",
    },
    {
        "id": "ventoux",
        "name": "Mont Ventoux",
        "race": "Tour de France",
        "region": "Provence, Frankreich",
        "distance_m": 2750,
        "real_distance_km": 22,
        "difficulty": 5,
        "opponents": 7,
        "obstacle_density": 0.7,
        "wind": 0.9,
        "heat": 0.8,
        "surface": "asphalt",
    },
    {
        "id": "mortirolo",
        "name": "Passo del Mortirolo",
        "race": "Giro d'Italia",
        "region": "Lombardei, Italien",
        "distance_m": 2600,
        "real_distance_km": 12,
        "difficulty": 5,
        "opponents": 6,
        "obstacle_density": 0.7,
        "wind": 0.4,
        "heat": 0.5,
        "surface": "asphalt",
    },
    {
        "id": "zoncolan",
        "name": "Monte Zoncolan",
        "race": "Giro d'Italia",
        "region": "Friaul, Italien",
        "distance_m": 2700,
        "real_distance_km": 10,
        "difficulty": 5,
        "opponents": 7,
        "obstacle_density": 0.7,
        "wind": 0.4,
        "heat": 0.6,
        "surface": "asphalt",
    },
    {
        "id": "stelvio",
        "name": "Passo dello Stelvio",
        "race": "Giro d'Italia – Cima Coppi",
        "region": "Südtirol, Italien",
        "distance_m": 3000,
        "real_distance_km": 24,
        "difficulty": 5,
        "opponents": 7,
        "obstacle_density": 0.6,
        "wind": 0.7,
        "heat": 0.4,
        "surface": "asphalt",
    },
    {
        "id": "angliru",
        "name": "Alto de l'Angliru",
        "race": "Vuelta a España",
        "region": "Asturien, Spanien",
        "distance_m": 2800,
        "real_distance_km": 12,
        "difficulty": 5,
        "opponents": 7,
        "obstacle_density": 0.8,
        "wind": 0.5,
        "heat": 0.5,
        "surface": "asphalt",
    },
    {
        "id": "lombardia",
        "name": "Il Lombardia",
        "race": "Monument – Klassiker der fallenden Blätter",
        "region": "Lombardei, Italien",
        "distance_m": 2200,
        "real_distance_km": 238,
        "difficulty": 3,
        "opponents": 6,
        "obstacle_density": 0.7,
        "wind": 0.3,
        "heat": 0.2,
        "surface": "asphalt",
    },
]


def route_by_id(rid):
    return next((r for r in ROUTES if r["id"] == rid), None)
